spring.application.name=gateway
server.port=8082


# Eureka client
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true


spring.cloud.gateway.server.webmvc.routes[0].id=api-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://api-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/**


management.endpoints.web.exposure.include=health,info