spring:
  application:
    name: api-service
server:
  port: '8080'
eureka:
  client:
    serviceUrl:
      defaultZone: '${EUREKA_URI:http://localhost:8761/eureka}'
  instance:
    prefer-ip-address: true

resilience4j:
  timelimiter:
    instances:
      dbService:
        timeout-duration: 2s
  retry:
    instances:
      dbService:
        max-attempts: 3
        wait-duration: 200ms
        retry-exceptions:
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - org.springframework.web.reactive.function.client.WebClientRequestException
  circuitbreaker:
    instances:
      dbService:
        sliding-window-size: 3
        failure-rate-threshold: 10
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3